import 'package:hive_flutter/hive_flutter.dart';

import '../../domain/models/reminder.dart';
import '../../domain/models/sheikh.dart';
import '../../domain/models/user_preferences.dart';


class StorageService {
  static final StorageService _instance = StorageService._internal();
  factory StorageService() => _instance;
  StorageService._internal();

  static const String _remindersBox = 'reminders';
  static const String _preferencesBox = 'preferences';
  static const String _sheikhsBox = 'sheikhs';
  static const String _downloadedAudioBox = 'downloaded_audio';

  bool _initialized = false;

  Future<void> initialize() async {
    if (_initialized) return;

    await Hive.initFlutter();

    // Register adapters (will be generated by build_runner)
    // For now, we'll use the JSON approach for complex objects

    await Hive.openBox(_remindersBox);
    await Hive.openBox(_preferencesBox);
    await Hive.openBox(_sheikhsBox);
    await Hive.openBox(_downloadedAudioBox);

    _initialized = true;
  }

  Box get _reminders => Hive.box(_remindersBox);
  Box get _preferences => Hive.box(_preferencesBox);
  Box get _sheikhs => Hive.box(_sheikhsBox);
  Box get _downloadedAudio => Hive.box(_downloadedAudioBox);

  // Reminders
  Future<void> saveReminder(Reminder reminder) async {
    await _reminders.put(reminder.id, reminder.toJson());
  }

  Future<void> deleteReminder(String id) async {
    await _reminders.delete(id);
  }

  List<Reminder> getAllReminders() {
    return _reminders.values
        .map((json) => Reminder.fromJson(Map<String, dynamic>.from(json)))
        .toList();
  }

  Reminder? getReminder(String id) {
    final json = _reminders.get(id);
    if (json == null) return null;
    return Reminder.fromJson(Map<String, dynamic>.from(json));
  }

  // User Preferences
  Future<void> savePreferences(UserPreferences prefs) async {
    await _preferences.put('user_prefs', prefs.toJson());
  }

  UserPreferences getPreferences() {
    final json = _preferences.get('user_prefs');
    if (json == null) return const UserPreferences();
    return UserPreferences.fromJson(Map<String, dynamic>.from(json));
  }

  // Favorites
  Future<void> toggleFavorite(String zikrId) async {
    final prefs = getPreferences();
    final favorites = List<String>.from(prefs.favoriteZikrIds);

    if (favorites.contains(zikrId)) {
      favorites.remove(zikrId);
    } else {
      favorites.add(zikrId);
    }

    await savePreferences(prefs.copyWith(favoriteZikrIds: favorites));
  }

  // Sheikhs
  Future<void> saveSheikh(Sheikh sheikh) async {
    await _sheikhs.put(sheikh.id, sheikh.toJson());
  }

  List<Sheikh> getAllSheikhs() {
    return _sheikhs.values
        .map((json) => Sheikh.fromJson(Map<String, dynamic>.from(json)))
        .toList();
  }

  Sheikh? getSheikh(String id) {
    final json = _sheikhs.get(id);
    if (json == null) return null;
    return Sheikh.fromJson(Map<String, dynamic>.from(json));
  }

  // Downloaded Audio
  Future<void> saveDownloadedAudio(DownloadedAudio audio) async {
    await _downloadedAudio.put(audio.id, audio.toJson());
  }

  Future<void> deleteDownloadedAudio(String id) async {
    await _downloadedAudio.delete(id);
  }

  List<DownloadedAudio> getAllDownloadedAudio() {
    return _downloadedAudio.values
        .map((json) => DownloadedAudio.fromJson(Map<String, dynamic>.from(json)))
        .toList();
  }

  DownloadedAudio? getDownloadedAudio(String zikrId, String sheikhId) {
    final key = '${zikrId}_$sheikhId';
    final json = _downloadedAudio.get(key);
    if (json == null) return null;
    return DownloadedAudio.fromJson(Map<String, dynamic>.from(json));
  }

  Future<void> clearAllData() async {
    await _reminders.clear();
    await _preferences.clear();
    await _sheikhs.clear();
    await _downloadedAudio.clear();
  }
}
