class SurahData {
  final int number;
  final String nameAr;
  final String nameEn;
  final String nameTranslation;
  final int verseCount;
  final String type; // Meccan or Medinan

  const SurahData({
    required this.number,
    required this.nameAr,
    required this.nameEn,
    required this.nameTranslation,
    required this.verseCount,
    required this.type,
  });

  static const List<SurahData> allSurahs = [
    SurahData(number: 1, nameAr: "الفاتحة", nameEn: "Al-Fatiha", nameTranslation: "The Opening", verseCount: 7, type: "Meccan"),
    SurahData(number: 2, nameAr: "البقرة", nameEn: "Al-Baqarah", nameTranslation: "The Cow", verseCount: 286, type: "Medinan"),
    SurahData(number: 3, nameAr: "آل عمران", nameEn: "Ali 'Imran", nameTranslation: "Family of Imran", verseCount: 200, type: "Medinan"),
    SurahData(number: 4, nameAr: "النساء", nameEn: "An-Nisa", nameTranslation: "The Women", verseCount: 176, type: "Medinan"),
    SurahData(number: 5, nameAr: "المائدة", nameEn: "Al-Ma'idah", nameTranslation: "The Table Spread", verseCount: 120, type: "Medinan"),
    SurahData(number: 6, nameAr: "الأنعام", nameEn: "Al-An'am", nameTranslation: "The Cattle", verseCount: 165, type: "Meccan"),
    SurahData(number: 7, nameAr: "الأعراف", nameEn: "Al-A'raf", nameTranslation: "The Heights", verseCount: 206, type: "Meccan"),
    SurahData(number: 8, nameAr: "الأنفال", nameEn: "Al-Anfal", nameTranslation: "The Spoils of War", verseCount: 75, type: "Medinan"),
    SurahData(number: 9, nameAr: "التوبة", nameEn: "At-Tawbah", nameTranslation: "The Repentance", verseCount: 129, type: "Medinan"),
    SurahData(number: 10, nameAr: "يونس", nameEn: "Yunus", nameTranslation: "Jonah", verseCount: 109, type: "Meccan"),
    SurahData(number: 11, nameAr: "هود", nameEn: "Hud", nameTranslation: "Hud", verseCount: 123, type: "Meccan"),
    SurahData(number: 12, nameAr: "يوسف", nameEn: "Yusuf", nameTranslation: "Joseph", verseCount: 111, type: "Meccan"),
    SurahData(number: 13, nameAr: "الرعد", nameEn: "Ar-Ra'd", nameTranslation: "The Thunder", verseCount: 43, type: "Medinan"),
    SurahData(number: 14, nameAr: "إبراهيم", nameEn: "Ibrahim", nameTranslation: "Abraham", verseCount: 52, type: "Meccan"),
    SurahData(number: 15, nameAr: "الحجر", nameEn: "Al-Hijr", nameTranslation: "The Rocky Tract", verseCount: 99, type: "Meccan"),
    SurahData(number: 16, nameAr: "النحل", nameEn: "An-Nahl", nameTranslation: "The Bee", verseCount: 128, type: "Meccan"),
    SurahData(number: 17, nameAr: "الإسراء", nameEn: "Al-Isra", nameTranslation: "The Night Journey", verseCount: 111, type: "Meccan"),
    SurahData(number: 18, nameAr: "الكهف", nameEn: "Al-Kahf", nameTranslation: "The Cave", verseCount: 110, type: "Meccan"),
    SurahData(number: 19, nameAr: "مريم", nameEn: "Maryam", nameTranslation: "Mary", verseCount: 98, type: "Meccan"),
    SurahData(number: 20, nameAr: "طه", nameEn: "Taha", nameTranslation: "Ta-Ha", verseCount: 135, type: "Meccan"),
    SurahData(number: 21, nameAr: "الأنبياء", nameEn: "Al-Anbiya", nameTranslation: "The Prophets", verseCount: 112, type: "Meccan"),
    SurahData(number: 22, nameAr: "الحج", nameEn: "Al-Hajj", nameTranslation: "The Pilgrimage", verseCount: 78, type: "Medinan"),
    SurahData(number: 23, nameAr: "المؤمنون", nameEn: "Al-Mu'minun", nameTranslation: "The Believers", verseCount: 118, type: "Meccan"),
    SurahData(number: 24, nameAr: "النور", nameEn: "An-Nur", nameTranslation: "The Light", verseCount: 64, type: "Medinan"),
    SurahData(number: 25, nameAr: "الفرقان", nameEn: "Al-Furqan", nameTranslation: "The Criterion", verseCount: 77, type: "Meccan"),
    SurahData(number: 26, nameAr: "الشعراء", nameEn: "Ash-Shu'ara", nameTranslation: "The Poets", verseCount: 227, type: "Meccan"),
    SurahData(number: 27, nameAr: "النمل", nameEn: "An-Naml", nameTranslation: "The Ant", verseCount: 93, type: "Meccan"),
    SurahData(number: 28, nameAr: "القصص", nameEn: "Al-Qasas", nameTranslation: "The Stories", verseCount: 88, type: "Meccan"),
    SurahData(number: 29, nameAr: "العنكبوت", nameEn: "Al-Ankabut", nameTranslation: "The Spider", verseCount: 69, type: "Meccan"),
    SurahData(number: 30, nameAr: "الروم", nameEn: "Ar-Rum", nameTranslation: "The Romans", verseCount: 60, type: "Meccan"),
    SurahData(number: 31, nameAr: "لقمان", nameEn: "Luqman", nameTranslation: "Luqman", verseCount: 34, type: "Meccan"),
    SurahData(number: 32, nameAr: "السجدة", nameEn: "As-Sajdah", nameTranslation: "The Prostration", verseCount: 30, type: "Meccan"),
    SurahData(number: 33, nameAr: "الأحزاب", nameEn: "Al-Ahzab", nameTranslation: "The Combined Forces", verseCount: 73, type: "Medinan"),
    SurahData(number: 34, nameAr: "سبأ", nameEn: "Saba", nameTranslation: "Sheba", verseCount: 54, type: "Meccan"),
    SurahData(number: 35, nameAr: "فاطر", nameEn: "Fatir", nameTranslation: "Originator", verseCount: 45, type: "Meccan"),
    SurahData(number: 36, nameAr: "يس", nameEn: "Ya-Sin", nameTranslation: "Ya Sin", verseCount: 83, type: "Meccan"),
    SurahData(number: 37, nameAr: "الصافات", nameEn: "As-Saffat", nameTranslation: "Those who set the Ranks", verseCount: 182, type: "Meccan"),
    SurahData(number: 38, nameAr: "ص", nameEn: "Sad", nameTranslation: "The Letter \"Saad\"", verseCount: 88, type: "Meccan"),
    SurahData(number: 39, nameAr: "الزمر", nameEn: "Az-Zumar", nameTranslation: "The Troops", verseCount: 75, type: "Meccan"),
    SurahData(number: 40, nameAr: "غافر", nameEn: "Ghafir", nameTranslation: "The Forgiver", verseCount: 85, type: "Meccan"),
    SurahData(number: 41, nameAr: "فصلت", nameEn: "Fussilat", nameTranslation: "Explained in Detail", verseCount: 54, type: "Meccan"),
    SurahData(number: 42, nameAr: "الشورى", nameEn: "Ash-Shura", nameTranslation: "The Consultation", verseCount: 53, type: "Meccan"),
    SurahData(number: 43, nameAr: "الزخرف", nameEn: "Az-Zukhruf", nameTranslation: "The Ornaments of Gold", verseCount: 89, type: "Meccan"),
    SurahData(number: 44, nameAr: "الدخان", nameEn: "Ad-Dukhan", nameTranslation: "The Smoke", verseCount: 59, type: "Meccan"),
    SurahData(number: 45, nameAr: "الجاثية", nameEn: "Al-Jathiyah", nameTranslation: "The Crouching", verseCount: 37, type: "Meccan"),
    SurahData(number: 46, nameAr: "الأحقاف", nameEn: "Al-Ahqaf", nameTranslation: "The Wind-Curved Sandhills", verseCount: 35, type: "Meccan"),
    SurahData(number: 47, nameAr: "محمد", nameEn: "Muhammad", nameTranslation: "Muhammad", verseCount: 38, type: "Medinan"),
    SurahData(number: 48, nameAr: "الفتح", nameEn: "Al-Fath", nameTranslation: "The Victory", verseCount: 29, type: "Medinan"),
    SurahData(number: 49, nameAr: "الحجرات", nameEn: "Al-Hujurat", nameTranslation: "The Rooms", verseCount: 18, type: "Medinan"),
    SurahData(number: 50, nameAr: "ق", nameEn: "Qaf", nameTranslation: "The Letter \"Qaf\"", verseCount: 45, type: "Meccan"),
    SurahData(number: 51, nameAr: "الذاريات", nameEn: "Adh-Dhariyat", nameTranslation: "The Winnowing Winds", verseCount: 60, type: "Meccan"),
    SurahData(number: 52, nameAr: "الطور", nameEn: "At-Tur", nameTranslation: "The Mount", verseCount: 49, type: "Meccan"),
    SurahData(number: 53, nameAr: "النجم", nameEn: "An-Najm", nameTranslation: "The Star", verseCount: 62, type: "Meccan"),
    SurahData(number: 54, nameAr: "القمر", nameEn: "Al-Qamar", nameTranslation: "The Moon", verseCount: 55, type: "Meccan"),
    SurahData(number: 55, nameAr: "الرحمن", nameEn: "Ar-Rahman", nameTranslation: "The Beneficent", verseCount: 78, type: "Medinan"),
    SurahData(number: 56, nameAr: "الواقعة", nameEn: "Al-Waqi'ah", nameTranslation: "The Inevitable", verseCount: 96, type: "Meccan"),
    SurahData(number: 57, nameAr: "الحديد", nameEn: "Al-Hadid", nameTranslation: "The Iron", verseCount: 29, type: "Medinan"),
    SurahData(number: 58, nameAr: "المجادلة", nameEn: "Al-Mujadila", nameTranslation: "The Pleading Woman", verseCount: 22, type: "Medinan"),
    SurahData(number: 59, nameAr: "الحشر", nameEn: "Al-Hashr", nameTranslation: "The Exile", verseCount: 24, type: "Medinan"),
    SurahData(number: 60, nameAr: "الممتحنة", nameEn: "Al-Mumtahanah", nameTranslation: "She that is to be examined", verseCount: 13, type: "Medinan"),
    SurahData(number: 61, nameAr: "الصف", nameEn: "As-Saff", nameTranslation: "The Ranks", verseCount: 14, type: "Medinan"),
    SurahData(number: 62, nameAr: "الجمعة", nameEn: "Al-Jumu'ah", nameTranslation: "The Congregation, Friday", verseCount: 11, type: "Medinan"),
    SurahData(number: 63, nameAr: "المنافقون", nameEn: "Al-Munafiqun", nameTranslation: "The Hypocrites", verseCount: 11, type: "Medinan"),
    SurahData(number: 64, nameAr: "التغابن", nameEn: "At-Taghabun", nameTranslation: "The Mutual Disillusion", verseCount: 18, type: "Medinan"),
    SurahData(number: 65, nameAr: "الطلاق", nameEn: "At-Talaq", nameTranslation: "The Divorce", verseCount: 12, type: "Medinan"),
    SurahData(number: 66, nameAr: "التحريم", nameEn: "At-Tahrim", nameTranslation: "The Prohibition", verseCount: 12, type: "Medinan"),
    SurahData(number: 67, nameAr: "الملك", nameEn: "Al-Mulk", nameTranslation: "The Sovereignty", verseCount: 30, type: "Meccan"),
    SurahData(number: 68, nameAr: "القلم", nameEn: "Al-Qalam", nameTranslation: "The Pen", verseCount: 52, type: "Meccan"),
    SurahData(number: 69, nameAr: "الحاقة", nameEn: "Al-Haqqah", nameTranslation: "The Reality", verseCount: 52, type: "Meccan"),
    SurahData(number: 70, nameAr: "المعارج", nameEn: "Al-Ma'arij", nameTranslation: "The Ascending Stairways", verseCount: 44, type: "Meccan"),
    SurahData(number: 71, nameAr: "نوح", nameEn: "Nuh", nameTranslation: "Noah", verseCount: 28, type: "Meccan"),
    SurahData(number: 72, nameAr: "الجن", nameEn: "Al-Jinn", nameTranslation: "The Jinn", verseCount: 28, type: "Meccan"),
    SurahData(number: 73, nameAr: "المزمل", nameEn: "Al-Muzzammil", nameTranslation: "The Enshrouded One", verseCount: 20, type: "Meccan"),
    SurahData(number: 74, nameAr: "المدثر", nameEn: "Al-Muddaththir", nameTranslation: "The Cloaked One", verseCount: 56, type: "Meccan"),
    SurahData(number: 75, nameAr: "القيامة", nameEn: "Al-Qiyamah", nameTranslation: "The Resurrection", verseCount: 40, type: "Meccan"),
    SurahData(number: 76, nameAr: "الإنسان", nameEn: "Al-Insan", nameTranslation: "The Man", verseCount: 31, type: "Medinan"),
    SurahData(number: 77, nameAr: "المرسلات", nameEn: "Al-Mursalat", nameTranslation: "The Emissaries", verseCount: 50, type: "Meccan"),
    SurahData(number: 78, nameAr: "النبأ", nameEn: "An-Naba", nameTranslation: "The Tidings", verseCount: 40, type: "Meccan"),
    SurahData(number: 79, nameAr: "النازعات", nameEn: "An-Nazi'at", nameTranslation: "Those who drag forth", verseCount: 46, type: "Meccan"),
    SurahData(number: 80, nameAr: "عبس", nameEn: "'Abasa", nameTranslation: "He Frowned", verseCount: 42, type: "Meccan"),
    SurahData(number: 81, nameAr: "التكوير", nameEn: "At-Takwir", nameTranslation: "The Overthrowing", verseCount: 29, type: "Meccan"),
    SurahData(number: 82, nameAr: "الإنفطار", nameEn: "Al-Infitar", nameTranslation: "The Cleaving", verseCount: 19, type: "Meccan"),
    SurahData(number: 83, nameAr: "المطففين", nameEn: "Al-Mutaffifin", nameTranslation: "The Defrauding", verseCount: 36, type: "Meccan"),
    SurahData(number: 84, nameAr: "الإنشقاق", nameEn: "Al-Inshiqaq", nameTranslation: "The Sundering", verseCount: 25, type: "Meccan"),
    SurahData(number: 85, nameAr: "البروج", nameEn: "Al-Buruj", nameTranslation: "The Mansions of the Stars", verseCount: 22, type: "Meccan"),
    SurahData(number: 86, nameAr: "الطارق", nameEn: "At-Tariq", nameTranslation: "The Morning Star", verseCount: 17, type: "Meccan"),
    SurahData(number: 87, nameAr: "الأعلى", nameEn: "Al-A'la", nameTranslation: "The Most High", verseCount: 19, type: "Meccan"),
    SurahData(number: 88, nameAr: "الغاشية", nameEn: "Al-Ghashiyah", nameTranslation: "The Overwhelming", verseCount: 26, type: "Meccan"),
    SurahData(number: 89, nameAr: "الفجر", nameEn: "Al-Fajr", nameTranslation: "The Dawn", verseCount: 30, type: "Meccan"),
    SurahData(number: 90, nameAr: "البلد", nameEn: "Al-Balad", nameTranslation: "The City", verseCount: 20, type: "Meccan"),
    SurahData(number: 91, nameAr: "الشمس", nameEn: "Ash-Shams", nameTranslation: "The Sun", verseCount: 15, type: "Meccan"),
    SurahData(number: 92, nameAr: "الليل", nameEn: "Al-Layl", nameTranslation: "The Night", verseCount: 21, type: "Meccan"),
    SurahData(number: 93, nameAr: "الضحى", nameEn: "Ad-Duhaa", nameTranslation: "The Morning Hours", verseCount: 11, type: "Meccan"),
    SurahData(number: 94, nameAr: "الشرح", nameEn: "Ash-Sharh", nameTranslation: "The Relief", verseCount: 8, type: "Meccan"),
    SurahData(number: 95, nameAr: "التين", nameEn: "At-Tin", nameTranslation: "The Fig", verseCount: 8, type: "Meccan"),
    SurahData(number: 96, nameAr: "العلق", nameEn: "Al-'Alaq", nameTranslation: "The Clot", verseCount: 19, type: "Meccan"),
    SurahData(number: 97, nameAr: "القدر", nameEn: "Al-Qadr", nameTranslation: "The Power", verseCount: 5, type: "Meccan"),
    SurahData(number: 98, nameAr: "البينة", nameEn: "Al-Bayyinah", nameTranslation: "The Clear Proof", verseCount: 8, type: "Medinan"),
    SurahData(number: 99, nameAr: "الزلزلة", nameEn: "Az-Zalzalah", nameTranslation: "The Earthquake", verseCount: 8, type: "Medinan"),
    SurahData(number: 100, nameAr: "العاديات", nameEn: "Al-'Adiyat", nameTranslation: "The Courser", verseCount: 11, type: "Meccan"),
    SurahData(number: 101, nameAr: "القارعة", nameEn: "Al-Qari'ah", nameTranslation: "The Calamity", verseCount: 11, type: "Meccan"),
    SurahData(number: 102, nameAr: "التكاثر", nameEn: "At-Takathur", nameTranslation: "The Rivalry in world increase", verseCount: 8, type: "Meccan"),
    SurahData(number: 103, nameAr: "العصر", nameEn: "Al-'Asr", nameTranslation: "The Declining Day", verseCount: 3, type: "Meccan"),
    SurahData(number: 104, nameAr: "الهمزة", nameEn: "Al-Humazah", nameTranslation: "The Traducer", verseCount: 9, type: "Meccan"),
    SurahData(number: 105, nameAr: "الفيل", nameEn: "Al-Fil", nameTranslation: "The Elephant", verseCount: 5, type: "Meccan"),
    SurahData(number: 106, nameAr: "قريش", nameEn: "Quraysh", nameTranslation: "Quraysh", verseCount: 4, type: "Meccan"),
    SurahData(number: 107, nameAr: "الماعون", nameEn: "Al-Ma'un", nameTranslation: "The Small Kindnesses", verseCount: 7, type: "Meccan"),
    SurahData(number: 108, nameAr: "الكوثر", nameEn: "Al-Kawthar", nameTranslation: "The Abundance", verseCount: 3, type: "Meccan"),
    SurahData(number: 109, nameAr: "الكافرون", nameEn: "Al-Kafirun", nameTranslation: "The Disbelievers", verseCount: 6, type: "Meccan"),
    SurahData(number: 110, nameAr: "النصر", nameEn: "An-Nasr", nameTranslation: "The Divine Support", verseCount: 3, type: "Medinan"),
    SurahData(number: 111, nameAr: "المسد", nameEn: "Al-Masad", nameTranslation: "The Palm Fiber", verseCount: 5, type: "Meccan"),
    SurahData(number: 112, nameAr: "الإخلاص", nameEn: "Al-Ikhlas", nameTranslation: "The Sincerity", verseCount: 4, type: "Meccan"),
    SurahData(number: 113, nameAr: "الفلق", nameEn: "Al-Falaq", nameTranslation: "The Daybreak", verseCount: 5, type: "Meccan"),
    SurahData(number: 114, nameAr: "الناس", nameEn: "An-Nas", nameTranslation: "Mankind", verseCount: 6, type: "Meccan"),
  ];
}
